name: e2e manual

# Run this workflow every time a new commit pushed to your repository
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  e2e-testing:
    # Name the Job
    name: End to end testing
    # Set the type of machine to run on
    runs-on: macos-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout
        uses: actions/checkout@v2
      - name: start testing
        run: npm run cypress:run:stage
